{% set name = "mono" %}
{% set version = "5.14.0.177" %}
{% set sha256 = "d4f5fa2e8188d66fbc8054f4145711e45c1faa6d070e63600efab93d1d189498" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: http://download.mono-project.com/sources/{{ name }}/{{ name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: True  # [win]

requirements:
  build:
    - perl
    - automake
    - libtool
    - pkg-config
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - gettext

test:
  commands:
    - mono --version
    - mono --help

about:
  home: http://www.mono-project.com
  license: MIT
  license_file: LICENSE
  summary: |
    Mono is a software platform designed to allow developers to easily create cross platform applications.
  description: |
    Mono is a software platform designed to allow developers to easily create cross platform applications.
    It is an open source implementation of Microsoft's .NET Framework based on the ECMA standards for C# and the Common Language Runtime.
  doc_url: http://www.mono-project.com/docs/
  dev_url: https://github.com/mono/mono

extra:
  recipe-maintainers:
    - bgruening
