{% set name = "mono" %}
{% set version = "6.12.0.90" %}
{% set sha256 = "51de5c02ad511333f93ff585bca54c8784de35af4ff27b759d16b46c4402cdac" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.mono-project.com/sources/mono/mono-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - perl
    - automake >=1.16
    - libtool
    - pkg-config
    - cmake
    - autoconf
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
    - make       # [unix]
  host:
    - zlib

test:
  commands:
    - mono --version
    - mono --help

about:
  home: http://www.mono-project.com
  license: MIT
  license_file: LICENSE
  summary: |
    Mono is a software platform designed to allow developers to easily create cross platform applications.
  description: |
    Mono is a software platform designed to allow developers to easily create cross platform applications.
    It is an open source implementation of Microsoft's .NET Framework based on the ECMA standards for C# and the Common Language Runtime.
  doc_url: http://www.mono-project.com/docs/
  dev_url: https://github.com/mono/mono

extra:
  recipe-maintainers:
    - bgruening
    - wolfv
