{% set version = "6.12.0.199" %}

package:
  name: mono
  version: {{ version }}

source:
  url: https://download.mono-project.com/sources/mono/mono-{{ version }}.tar.xz
  sha256: c0850d545353a6ba2238d45f0914490c6a14a0017f151d3905b558f033478ef5

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - perl
    - automake >=1.16
    - libtool
    - pkg-config
    - cmake
    - autoconf
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
    - make       # [unix]
  host:
    - zlib

test:
  commands:
    - mono --version
    - mono --help

about:
  home: http://www.mono-project.com
  license: MIT
  license_file: LICENSE
  summary: |
    Mono is a software platform designed to allow developers to easily create cross platform applications.
  description: |
    Mono is a software platform designed to allow developers to easily create cross platform applications.
    It is an open source implementation of Microsoft's .NET Framework based on the ECMA standards for C# and the Common Language Runtime.
  doc_url: http://www.mono-project.com/docs/
  dev_url: https://github.com/mono/mono

extra:
  recipe-maintainers:
    - bgruening
    - wolfv
    - hmaarrfk  # happy to help review and merge other's PRs.
