conda_forge_output_validation: true
provider:
  linux_aarch64: default
build_platform:
  linux_aarch64: linux_64
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
