travis:
  secure:
    BINSTAR_TOKEN: W8sWwp/cEk5ey+ffcXpcTdLg/zX6GwD/CqoYDq8bEkO1b7mUZ0HQ6mDE9S+L7z/kDb68a1qheeDG4vNZCA7+XYeO/BfqjJFAvTq8HbRlalQUXQ80fh3DPKoFvVwtDPvHeVTMboeSb3v2ZrraUV7eanH+Qia2EgoebLbbHorq0xXtP6CYH0FeP5sGD65SA67mzDGL22DnesMEBCo0JUVx+3rWFqtP8dG2/9pXkggQ0CTQ+WEKp+7lE+fz4zcHAa4NNngkl5SfJrY/li86OLbyGn/mVcHmNHNMhdA93mDN2Yfc2VHkuFhkvjqT6o/9pasbYlSWdEslQBpjvLwa86IX89Mjr5pGA7TjPdLJ7hmC9+oYTz2PIPWR4w2Vv0BXd4ttx5ShtaQtQEsdWzsAYxZvLMjFOM3rvCdojklKJ9ADWJEBA+0Wcn0fJqJsojkNL1f2wzTzXbhCIfRe5dLbjnQneRQD8REz4ovpuOVzn9iuJPxb3PzpG06DNvtxrXpm6EhRgThLogQ8ZPxnSDlMzhXeVpsxBjRwclw2967NlMfq/Mx94mTa73O/r7FXvWHVu7LGBeSFal5/8Jx43GoNCp86f64H4FjHeAZDt6sInP9wxvvFwGPXVKTS4AYCkowpnblwH/gHxJtG2ZVFM74rMcwcNwRUTIZTfv5Z00DQ16xDLGY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
